imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


parameters:
    locale: fr


framework:
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/bootstrap_3_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        path: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    spool: { type: memory }

    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    auth_mode: '%mailer_auth_mode%'
    port:      '%mailer_port%'


# FOSUB Config
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"


vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '/uploads/images/products'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/products'


easy_admin:
    site_name: 'Kubithon'
    design:
        brand_color: '#3498db'
        menu:
            - { entity: 'User', icon: 'users' }
            - { entity: 'Product', icon: 'shopping-cart' }
            - { entity: 'Goal', icon: 'trophy' }

    entities:
        User:
            label: 'Utilisateurs'
            class: AppBundle\Entity\User
            disabled_actions: ['new']
            list:
                title: 'Liste des utilisateurs'
                fields:
                    - 'id'
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'balance', label: 'Crédits', type: 'integer' }
                    - { property: 'crack', label: 'Compte crack', type: 'boolean' }

            edit:
                title: 'Editer un utilisateur (#%%entity_id%%)'
                fields:
                    - { property: 'id', label: 'Id', type_options: { disabled: true } }
                    - { property: 'uuid', label: 'UUID', type_options: { disabled: true } }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'balance', label: 'Crédits', type: 'integer'}
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        Product:
            label: 'Produits'
            class: Kubithon\ShopBundle\Entity\Product
            list:
                title: 'Liste des produits'
                fields:
                    - 'id'
                    - { property: 'name', label: 'Nom' }
                    - { property: 'price', label: 'Prix', type: 'integer' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '/uploads/images/products' }
                    - { property: 'activated', label: 'Activé', type: 'toggle' }

            new:
                title: 'Nouveau produit'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'price', label: 'Prix', type: 'integer' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', base_path: '/uploads/images/products' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }

            edit:
                title: 'Supprimer un produit'
                fields:
                     - { property: 'id', label: 'Id', type_options: { disabled: true } }

        Goal:
            label: 'Objectifs de dons'
            class: AppBundle\Entity\Goal
            list:
                title: 'Liste des objectifs'
                fields:
                    - 'id'
                    - { property: 'amount', label: 'Montant minimal' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'achieved', label: 'Atteint', type: 'toggle' }

            new:
                title: 'Nouvel objectif (sera affiché en direct)'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'amount', label: 'Montant minimal' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'achievedMessage', label: "Message affiché lorsqu'atteint" }
                    - { property: 'achievedLongmessage', label: "Message détaillé lorsqu'atteint" }

            edit:
                title: 'Modifier un objectif (sera mis à jour en direct)'
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'amount', label: 'Montant minimal' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'achievedMessage', label: "Message affiché lorsqu'atteint" }
                    - { property: 'achievedLongmessage', label: "Message détaillé lorsqu'atteint" }

            delete:
                title: 'Supprimer un objectif (sera retiré en direct)'
                fields:
                     - { property: 'id', label: 'ID', type_options: { disabled: true } }
