services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Kubithon\ApiBundle\Controller\:
        resource: '../../src/Kubithon/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app.service.paypal.payment:
        class: Kubithon\ShopBundle\Service\PaypalPaymentService
        public: true

